export const PATHS = {
  HOME: "/",
  FOR_YOU: "/for_you",
  FOLLOWING: "/following",
  GHOST_POSTS: "/ghost-posts",
  USER_PROFILE: "/:username",
  POST_DETAIL: "/:username/post/:id",
  SEARCH: "/search",
  ACTIVITY: "/activity",
  PROFILE: "/profile",
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  NOT_FOUND: "*",
};
